package com.ioyouyun.group.model;

/**
 * Created by 卫彪 on 2016/11/23.
 *
 * Automatic generated by Gson
 */
public class ChatRoomInfoEntity {


    private String uid;
    private int role;
    private PropsEntity props;

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public int getRole() {
        return role;
    }

    public void setRole(int role) {
        this.role = role;
    }

    public PropsEntity getProps() {
        return props;
    }

    public void setProps(PropsEntity props) {
        this.props = props;
    }

    public static class PropsEntity {
        private boolean show_mark;
        private String remind;
        private boolean gag;

        public boolean isShow_mark() {
            return show_mark;
        }

        public void setShow_mark(boolean show_mark) {
            this.show_mark = show_mark;
        }

        public String getRemind() {
            return remind;
        }

        public void setRemind(String remind) {
            this.remind = remind;
        }

        public boolean isGag() {
            return gag;
        }

        public void setGag(boolean gag) {
            this.gag = gag;
        }
    }
}
