package com.ioyouyun.group.model;

/**
 * Created by 卫彪 on 2016/7/8.
 * Automatic generated by Gson
 */
public class GroupMemberEntity {

    private int region;
    private int phone;
    private boolean allow_search_me_by_weibo;
    private boolean allow_weibo_friend_auto_add;
    private boolean allow_search_me_by_address_book;
    private int statuses_count;
    private String type;
    private boolean allow_search_me_by_weimi;
    private String id;
    private boolean following;
    private String level;

    private GroupuserPropsEntity groupuser_props;
    private boolean reply_auto_add_friend;
    private String activetime;
    private int role;
    private String gender;
    private int grade;
    private String created_at;
    private boolean allow_weibo_friend_match;
    private boolean forbid_stranger_follow;
    private int followers_count;
    private boolean add_friend_verify;
    private boolean show_weibo;
    private int bi_followers_count;
    private boolean rec_stranger_activity_group_chat;
    private boolean geo_enabled;
    private String nickname;
    private boolean rec_stranger_dm;

    private SubtagInfoEntity subtag_info;
    private boolean allow_address_book_match;
    private boolean allow_address_book_auto_add;
    private String jointime;
    private int friends_count;
    private boolean follow_me;

    public int getRegion() {
        return region;
    }

    public void setRegion(int region) {
        this.region = region;
    }

    public int getPhone() {
        return phone;
    }

    public void setPhone(int phone) {
        this.phone = phone;
    }

    public boolean isAllow_search_me_by_weibo() {
        return allow_search_me_by_weibo;
    }

    public void setAllow_search_me_by_weibo(boolean allow_search_me_by_weibo) {
        this.allow_search_me_by_weibo = allow_search_me_by_weibo;
    }

    public boolean isAllow_weibo_friend_auto_add() {
        return allow_weibo_friend_auto_add;
    }

    public void setAllow_weibo_friend_auto_add(boolean allow_weibo_friend_auto_add) {
        this.allow_weibo_friend_auto_add = allow_weibo_friend_auto_add;
    }

    public boolean isAllow_search_me_by_address_book() {
        return allow_search_me_by_address_book;
    }

    public void setAllow_search_me_by_address_book(boolean allow_search_me_by_address_book) {
        this.allow_search_me_by_address_book = allow_search_me_by_address_book;
    }

    public int getStatuses_count() {
        return statuses_count;
    }

    public void setStatuses_count(int statuses_count) {
        this.statuses_count = statuses_count;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isAllow_search_me_by_weimi() {
        return allow_search_me_by_weimi;
    }

    public void setAllow_search_me_by_weimi(boolean allow_search_me_by_weimi) {
        this.allow_search_me_by_weimi = allow_search_me_by_weimi;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public boolean isFollowing() {
        return following;
    }

    public void setFollowing(boolean following) {
        this.following = following;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public GroupuserPropsEntity getGroupuser_props() {
        return groupuser_props;
    }

    public void setGroupuser_props(GroupuserPropsEntity groupuser_props) {
        this.groupuser_props = groupuser_props;
    }

    public boolean isReply_auto_add_friend() {
        return reply_auto_add_friend;
    }

    public void setReply_auto_add_friend(boolean reply_auto_add_friend) {
        this.reply_auto_add_friend = reply_auto_add_friend;
    }

    public String getActivetime() {
        return activetime;
    }

    public void setActivetime(String activetime) {
        this.activetime = activetime;
    }

    public int getRole() {
        return role;
    }

    public void setRole(int role) {
        this.role = role;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public int getGrade() {
        return grade;
    }

    public void setGrade(int grade) {
        this.grade = grade;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public boolean isAllow_weibo_friend_match() {
        return allow_weibo_friend_match;
    }

    public void setAllow_weibo_friend_match(boolean allow_weibo_friend_match) {
        this.allow_weibo_friend_match = allow_weibo_friend_match;
    }

    public boolean isForbid_stranger_follow() {
        return forbid_stranger_follow;
    }

    public void setForbid_stranger_follow(boolean forbid_stranger_follow) {
        this.forbid_stranger_follow = forbid_stranger_follow;
    }

    public int getFollowers_count() {
        return followers_count;
    }

    public void setFollowers_count(int followers_count) {
        this.followers_count = followers_count;
    }

    public boolean isAdd_friend_verify() {
        return add_friend_verify;
    }

    public void setAdd_friend_verify(boolean add_friend_verify) {
        this.add_friend_verify = add_friend_verify;
    }

    public boolean isShow_weibo() {
        return show_weibo;
    }

    public void setShow_weibo(boolean show_weibo) {
        this.show_weibo = show_weibo;
    }

    public int getBi_followers_count() {
        return bi_followers_count;
    }

    public void setBi_followers_count(int bi_followers_count) {
        this.bi_followers_count = bi_followers_count;
    }

    public boolean isRec_stranger_activity_group_chat() {
        return rec_stranger_activity_group_chat;
    }

    public void setRec_stranger_activity_group_chat(boolean rec_stranger_activity_group_chat) {
        this.rec_stranger_activity_group_chat = rec_stranger_activity_group_chat;
    }

    public boolean isGeo_enabled() {
        return geo_enabled;
    }

    public void setGeo_enabled(boolean geo_enabled) {
        this.geo_enabled = geo_enabled;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public boolean isRec_stranger_dm() {
        return rec_stranger_dm;
    }

    public void setRec_stranger_dm(boolean rec_stranger_dm) {
        this.rec_stranger_dm = rec_stranger_dm;
    }

    public SubtagInfoEntity getSubtag_info() {
        return subtag_info;
    }

    public void setSubtag_info(SubtagInfoEntity subtag_info) {
        this.subtag_info = subtag_info;
    }

    public boolean isAllow_address_book_match() {
        return allow_address_book_match;
    }

    public void setAllow_address_book_match(boolean allow_address_book_match) {
        this.allow_address_book_match = allow_address_book_match;
    }

    public boolean isAllow_address_book_auto_add() {
        return allow_address_book_auto_add;
    }

    public void setAllow_address_book_auto_add(boolean allow_address_book_auto_add) {
        this.allow_address_book_auto_add = allow_address_book_auto_add;
    }

    public String getJointime() {
        return jointime;
    }

    public void setJointime(String jointime) {
        this.jointime = jointime;
    }

    public int getFriends_count() {
        return friends_count;
    }

    public void setFriends_count(int friends_count) {
        this.friends_count = friends_count;
    }

    public boolean isFollow_me() {
        return follow_me;
    }

    public void setFollow_me(boolean follow_me) {
        this.follow_me = follow_me;
    }

    public static class GroupuserPropsEntity {
        private boolean show_mark;
        private String remind;
        private boolean gag;

        public boolean isShow_mark() {
            return show_mark;
        }

        public void setShow_mark(boolean show_mark) {
            this.show_mark = show_mark;
        }

        public String getRemind() {
            return remind;
        }

        public void setRemind(String remind) {
            this.remind = remind;
        }

        public boolean isGag() {
            return gag;
        }

        public void setGag(boolean gag) {
            this.gag = gag;
        }
    }

    public static class SubtagInfoEntity {
        private String subtag_name;
        private int subtag_gid;
        private boolean can_show;

        public String getSubtag_name() {
            return subtag_name;
        }

        public void setSubtag_name(String subtag_name) {
            this.subtag_name = subtag_name;
        }

        public int getSubtag_gid() {
            return subtag_gid;
        }

        public void setSubtag_gid(int subtag_gid) {
            this.subtag_gid = subtag_gid;
        }

        public boolean isCan_show() {
            return can_show;
        }

        public void setCan_show(boolean can_show) {
            this.can_show = can_show;
        }
    }
}
