package com.ioyouyun.group.model;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Created by 卫彪 on 2016/7/5.
 *
 * Automatic generated by Gson
 */
public class GroupInfoEntity implements Parcelable{

    protected GroupInfoEntity(Parcel in) {
        feedCount = in.readInt();
        settings = in.readString();
        creatorId = in.readInt();
        creadate = in.readString();
        needPay = in.readInt();
        cat1 = in.readInt();
        level = in.readInt();
        group_remind = in.readString();
        cat3 = in.readInt();
        cat2 = in.readInt();
        maxMembers = in.readInt();
        name = in.readString();
        activetime = in.readInt();
        gid = in.readString();
        role = in.readInt();
        members = in.readInt();
        intra = in.readString();
        addGroupVerify = in.readInt();
    }

    public static final Creator<GroupInfoEntity> CREATOR = new Creator<GroupInfoEntity>() {
        @Override
        public GroupInfoEntity createFromParcel(Parcel in) {
            return new GroupInfoEntity(in);
        }

        @Override
        public GroupInfoEntity[] newArray(int size) {
            return new GroupInfoEntity[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(feedCount);
        dest.writeString(settings);
        dest.writeInt(creatorId);
        dest.writeString(creadate);
        dest.writeInt(needPay);
        dest.writeInt(cat1);
        dest.writeInt(level);
        dest.writeString(group_remind);
        dest.writeInt(cat3);
        dest.writeInt(cat2);
        dest.writeInt(maxMembers);
        dest.writeString(name);
        dest.writeInt(activetime);
        dest.writeString(gid);
        dest.writeInt(role);
        dest.writeInt(members);
        dest.writeString(intra);
        dest.writeInt(addGroupVerify);
    }

    private int feedCount;
    private String settings;
    private int creatorId;

    private SubtagInfoEntity subtag_info;
    private String creadate;
    private int needPay;
    private int cat1;
    private int level;
    private String group_remind;
    private int cat3;
    private int cat2;
    private int maxMembers;
    private String name;
    private int activetime;
    private String gid;
    private int role;

    private PropsEntity props;
    private int members;
    private String intra;

    private int addGroupVerify; // 加群验证

    public GroupInfoEntity() {
    }

    public int getAddGroupVerify() {
        return addGroupVerify;
    }

    public void setAddGroupVerify(int addGroupVerify) {
        this.addGroupVerify = addGroupVerify;
    }

    public int getFeedCount() {
        return feedCount;
    }

    public void setFeedCount(int feedCount) {
        this.feedCount = feedCount;
    }

    public String getSettings() {
        return settings;
    }

    public void setSettings(String settings) {
        this.settings = settings;
    }

    public int getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(int creatorId) {
        this.creatorId = creatorId;
    }

    public SubtagInfoEntity getSubtag_info() {
        return subtag_info;
    }

    public void setSubtag_info(SubtagInfoEntity subtag_info) {
        this.subtag_info = subtag_info;
    }

    public String getCreadate() {
        return creadate;
    }

    public void setCreadate(String creadate) {
        this.creadate = creadate;
    }

    public int getNeedPay() {
        return needPay;
    }

    public void setNeedPay(int needPay) {
        this.needPay = needPay;
    }

    public int getCat1() {
        return cat1;
    }

    public void setCat1(int cat1) {
        this.cat1 = cat1;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public String getGroup_remind() {
        return group_remind;
    }

    public void setGroup_remind(String group_remind) {
        this.group_remind = group_remind;
    }

    public int getCat3() {
        return cat3;
    }

    public void setCat3(int cat3) {
        this.cat3 = cat3;
    }

    public int getCat2() {
        return cat2;
    }

    public void setCat2(int cat2) {
        this.cat2 = cat2;
    }

    public int getMaxMembers() {
        return maxMembers;
    }

    public void setMaxMembers(int maxMembers) {
        this.maxMembers = maxMembers;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getActivetime() {
        return activetime;
    }

    public void setActivetime(int activetime) {
        this.activetime = activetime;
    }

    public String getGid() {
        return gid;
    }

    public void setGid(String gid) {
        this.gid = gid;
    }

    public int getRole() {
        return role;
    }

    public void setRole(int role) {
        this.role = role;
    }

    public PropsEntity getProps() {
        return props;
    }

    public void setProps(PropsEntity props) {
        this.props = props;
    }

    public int getMembers() {
        return members;
    }

    public void setMembers(int members) {
        this.members = members;
    }

    public String getIntra() {
        return intra;
    }

    public void setIntra(String intra) {
        this.intra = intra;
    }

    public static class SubtagInfoEntity {
        private String subtag_name;
        private int subtag_gid;
        private boolean can_show;

        public String getSubtag_name() {
            return subtag_name;
        }

        public void setSubtag_name(String subtag_name) {
            this.subtag_name = subtag_name;
        }

        public int getSubtag_gid() {
            return subtag_gid;
        }

        public void setSubtag_gid(int subtag_gid) {
            this.subtag_gid = subtag_gid;
        }

        public boolean isCan_show() {
            return can_show;
        }

        public void setCan_show(boolean can_show) {
            this.can_show = can_show;
        }
    }

    public static class PropsEntity {
        private int auto_upgrade;
        private int app_id;

        public int getAuto_upgrade() {
            return auto_upgrade;
        }

        public void setAuto_upgrade(int auto_upgrade) {
            this.auto_upgrade = auto_upgrade;
        }

        public int getApp_id() {
            return app_id;
        }

        public void setApp_id(int app_id) {
            this.app_id = app_id;
        }
    }
}
