package com.ioyouyun.contacts.model;

/**
 * Created by 卫彪 on 2016/7/7.
 *
 * Automatic generated by Gson
 */
public class NearbyUserEntity {

    private boolean isChecked = false; // 标识CheckBox是否选中
    private boolean reply_auto_add_friend;
    private String gender;
    private int distance;
    private String created_at;
    private String type;
    private boolean rec_stranger_activity_group_chat;
    private boolean allow_address_book_match;
    private boolean rec_stranger_dm;
    private boolean allow_address_book_auto_add;
    private String nickname;
    private long ctime;
    private String id;
    private boolean geo_enabled;
    private boolean allow_search_me_by_weibo;
    private String level;
    private boolean show_weibo;
    private boolean allow_weibo_friend_match;
    private boolean allow_search_me_by_weimi;
    private int phone;
    private int grade;
    private boolean allow_weibo_friend_auto_add;
    private boolean allow_search_me_by_address_book;
    private boolean forbid_stranger_follow;
    private int region;
    private boolean add_friend_verify;

    public boolean isChecked() {
        return isChecked;
    }

    public void setChecked(boolean checked) {
        isChecked = checked;
    }

    public boolean isReply_auto_add_friend() {
        return reply_auto_add_friend;
    }

    public void setReply_auto_add_friend(boolean reply_auto_add_friend) {
        this.reply_auto_add_friend = reply_auto_add_friend;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public int getDistance() {
        return distance;
    }

    public void setDistance(int distance) {
        this.distance = distance;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isRec_stranger_activity_group_chat() {
        return rec_stranger_activity_group_chat;
    }

    public void setRec_stranger_activity_group_chat(boolean rec_stranger_activity_group_chat) {
        this.rec_stranger_activity_group_chat = rec_stranger_activity_group_chat;
    }

    public boolean isAllow_address_book_match() {
        return allow_address_book_match;
    }

    public void setAllow_address_book_match(boolean allow_address_book_match) {
        this.allow_address_book_match = allow_address_book_match;
    }

    public boolean isRec_stranger_dm() {
        return rec_stranger_dm;
    }

    public void setRec_stranger_dm(boolean rec_stranger_dm) {
        this.rec_stranger_dm = rec_stranger_dm;
    }

    public boolean isAllow_address_book_auto_add() {
        return allow_address_book_auto_add;
    }

    public void setAllow_address_book_auto_add(boolean allow_address_book_auto_add) {
        this.allow_address_book_auto_add = allow_address_book_auto_add;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public long getCtime() {
        return ctime;
    }

    public void setCtime(long ctime) {
        this.ctime = ctime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public boolean isGeo_enabled() {
        return geo_enabled;
    }

    public void setGeo_enabled(boolean geo_enabled) {
        this.geo_enabled = geo_enabled;
    }

    public boolean isAllow_search_me_by_weibo() {
        return allow_search_me_by_weibo;
    }

    public void setAllow_search_me_by_weibo(boolean allow_search_me_by_weibo) {
        this.allow_search_me_by_weibo = allow_search_me_by_weibo;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public boolean isShow_weibo() {
        return show_weibo;
    }

    public void setShow_weibo(boolean show_weibo) {
        this.show_weibo = show_weibo;
    }

    public boolean isAllow_weibo_friend_match() {
        return allow_weibo_friend_match;
    }

    public void setAllow_weibo_friend_match(boolean allow_weibo_friend_match) {
        this.allow_weibo_friend_match = allow_weibo_friend_match;
    }

    public boolean isAllow_search_me_by_weimi() {
        return allow_search_me_by_weimi;
    }

    public void setAllow_search_me_by_weimi(boolean allow_search_me_by_weimi) {
        this.allow_search_me_by_weimi = allow_search_me_by_weimi;
    }

    public int getPhone() {
        return phone;
    }

    public void setPhone(int phone) {
        this.phone = phone;
    }

    public int getGrade() {
        return grade;
    }

    public void setGrade(int grade) {
        this.grade = grade;
    }

    public boolean isAllow_weibo_friend_auto_add() {
        return allow_weibo_friend_auto_add;
    }

    public void setAllow_weibo_friend_auto_add(boolean allow_weibo_friend_auto_add) {
        this.allow_weibo_friend_auto_add = allow_weibo_friend_auto_add;
    }

    public boolean isAllow_search_me_by_address_book() {
        return allow_search_me_by_address_book;
    }

    public void setAllow_search_me_by_address_book(boolean allow_search_me_by_address_book) {
        this.allow_search_me_by_address_book = allow_search_me_by_address_book;
    }

    public boolean isForbid_stranger_follow() {
        return forbid_stranger_follow;
    }

    public void setForbid_stranger_follow(boolean forbid_stranger_follow) {
        this.forbid_stranger_follow = forbid_stranger_follow;
    }

    public int getRegion() {
        return region;
    }

    public void setRegion(int region) {
        this.region = region;
    }

    public boolean isAdd_friend_verify() {
        return add_friend_verify;
    }

    public void setAdd_friend_verify(boolean add_friend_verify) {
        this.add_friend_verify = add_friend_verify;
    }
}
